<%@ Page Language="C#" MasterPageFile="~/Customer.master" AutoEventWireup="true" CodeFile="frmViewCart.aspx.cs" Inherits="frmAddToCart" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style3
        {
            height: 23px;
        }
        .style4
        {
            width: 299px;
        }
        .style5
        {
            width: 467px;
        }
    </style>
    <script type="text/css">
<P style="margin-bottom:0px; margin-left:43px">
 .ResizeDataList</P>
<P style="margin-bottom:0px; margin-left:43px; line-height:16px">
 {</P>
<P style="margin-bottom:0px; margin-left:57px; line-height:16px">
 height:100%;width:100%;</P>
<P style="margin-bottom:0px; margin-left:28px; text-indent:14px; line-height:16px">
 } </script>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <table class="style1">
        <tr>
            <td class="style3" colspan="2">
            </td>
            <td class="style3">
            </td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                <asp:Label ID="lblMsg" runat="server" ForeColor="Red" 
                    style="font-size: x-large"></asp:Label>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td style="text-align: center" class="style4">
                &nbsp;</td>
            <td style="text-align: center" class="style5">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" 
                    AutoGenerateSelectButton="True" CellPadding="4" ForeColor="#333333" 
                    GridLines="None" onrowcommand="GridView1_RowCommand" 
                    onrowdeleting="GridView1_RowDeleting" Width="280px">
                    <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                    <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                    <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                    <AlternatingRowStyle BackColor="White" />
                </asp:GridView>
            </td>
            <td style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                <asp:Label ID="Label2" runat="server" Text="Total Amount:"></asp:Label>
&nbsp;<asp:Label ID="Label1" runat="server" style="font-weight: 700; font-size: x-large"></asp:Label></td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                    <asp:Button ID="btnProceed" runat="server" Text="Proceed to Checkout" BackColor="#002200" 
                        Font-Bold="True" Font-Size="Large" ForeColor="White" Height="28px" 
                        onclick="btnProceed_Click" style="top: 407px; left: 505px; " 
                        Width="205px" />
                    </td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
        <tr>
            <td colspan="3" style="text-align: center">
                &nbsp;</td>
        </tr>
    </table>

</asp:Content>

